### ISSUE TITLE
Support lists for container commands

### ISSUE THREAD

**Issue by exterrestris** [exterrestris/ansible-role-docker-compose#7]
docker-compose.yml allows specifying commands in a list:
```
services:
  container:
    command:
      - command 1
      - command 2
```
